---
- name: Harden and configure secure VPS
  hosts: vps
  become: yes
  vars_files:
    - vault.yml
  vars:
    admin_user: viktor
    ssh_public_key_path: "~/.ssh/id_ed25519_vps.pub"
  roles:
    - users
    - hardening
    - tailscale
    - firewall
    - backup
